### ISSUE TITLE
SSL cannot connect, ArgumentOutOfRangeException exception

### ISSUE THREAD

**Issue by ivan7wl** [jchristn/WatsonTcp#158]
I'm running the tests under Linux, dotnet 6.0, but SSL cannot connect.

Test.Server:
```
Test.Server$ dotnet run --framework net6.0
Server IP: [localhost] 
Server port: [9000] 
Use SSL: [y/N]? y
Certificate file: [test.pfx] 
Certificate password: [password] 
Accept invalid certs: [Y/n]? y
Mutually authenticate: [y/N]? n
[Info     ] [WatsonTcpServer] starting with SSL on 127.0.0.1:9000
Server started
Command [? for help]: 
Command [? for help]: 
Command [? for help]: 
Command [? for help]: 
Command [? for help]: [Debug    ] [WatsonTcpServer] accepted connection from 127.0.0.1:36244
[Error    ] [WatsonTcpServer] disconnected during SSL/TLS establishment with 127.0.0.1:36244 (Tls12): 
{
  "ClassName": "System.IO.IOException",
  "Message": "Unable to read data from the transport connection: Connection reset by peer.",
  "Data": null,
  "InnerException": {
    "ClassName": "System.Net.Sockets.SocketException",
    "Message": "Connection reset by peer",
    "Data": null,
    "InnerException": null,
    "HelpURL": null,
    "StackTraceString": null,
    "RemoteStackTraceString": null,
    "RemoteStackIndex": 0,
    "ExceptionMethod": null,
    "HResult": -2147467259,
    "Source": null,
    "WatsonBuckets": null,
    "NativeErrorCode": 104
  },
  "HelpURL": null,
  "StackTraceString": "   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)\n   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)\n   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|187_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)\n   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)\n   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)\n   at WatsonTcp.WatsonTcpServer.StartTls(ClientMetadata client) in /home/ivan_wl/devel/dotnet/WatsonTcp/WatsonTcp/WatsonTcpServer.cs:line 848",
  "RemoteStackTraceString": null,
  "RemoteStackIndex": 0,
  "ExceptionMethod": null,
  "HResult": -2146232800,
  "Source": "System.Net.Sockets",
  "WatsonBuckets": null
}
```

Test.Client:
```
Test.Client$ dotnet run --framework net6.0
Server IP: [localhost] 
Server port: [9000] 
Use SSL: [y/N]? y
Supply SSL certificate: [y/N]? n
Accept invalid certs: [Y/n]? y
Mutually authenticate: [y/N]? n
[Info     ] [WatsonTcpClient] connecting with SSL to localhost:9000
[Error    ] [WatsonTcpClient] exception encountered: 
{
  "ClassName": "System.ArgumentOutOfRangeException",
  "Message": "Index was out of range. Must be non-negative and less than the size of the collection.",
  "Data": null,
  "InnerException": null,
  "HelpURL": null,
  "StackTraceString": "   at System.Collections.CollectionBase.System.Collections.IList.get_Item(Int32 index)\n   at System.Security.Cryptography.X509Certificates.X509CertificateCollection.get_Item(Int32 index)\n   at WatsonTcp.WatsonTcpClientSslConfiguration.DefaultSelectClientCertificate(Object sender, String targetHost, X509CertificateCollection clientCertificates, X509Certificate serverCertificate, String[] acceptableIssuers) in /home/ivan_wl/devel/dotnet/WatsonTcp/WatsonTcp/WatsonTcpClientSslConfiguration.cs:line 108\n   at System.Net.Security.SslStream.UserCertSelectionCallbackWrapper(String targetHost, X509CertificateCollection localCertificates, X509Certificate remoteCertificate, String[] acceptableIssuers)\n   at System.Net.Security.SecureChannel.AcquireClientCredentials(Byte[]& thumbPrint)\n   at System.Net.Security.SecureChannel.GenerateToken(ReadOnlySpan`1 inputBuffer, Byte[]& output)\n   at System.Net.Security.SecureChannel.NextMessage(ReadOnlySpan`1 incomingBuffer)\n   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)\n   at System.Net.Security.SslStream.AuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions)\n   at System.Net.Security.SslStream.AuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)\n   at WatsonTcp.WatsonTcpClient.Connect() in /home/ivan_wl/devel/dotnet/WatsonTcp/WatsonTcp/WatsonTcpClient.cs:line 374",
  "RemoteStackTraceString": null,
  "RemoteStackIndex": 0,
  "ExceptionMethod": null,
  "HResult": -2146233086,
  "Source": "System.Collections.NonGeneric",
  "WatsonBuckets": null,
  "ParamName": "index",
  "ActualValue": null
}
Unhandled exception. System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.CollectionBase.System.Collections.IList.get_Item(Int32 index)
   at System.Security.Cryptography.X509Certificates.X509CertificateCollection.get_Item(Int32 index)
   at WatsonTcp.WatsonTcpClientSslConfiguration.DefaultSelectClientCertificate(Object sender, String targetHost, X509CertificateCollection clientCertificates, X509Certificate serverCertificate, String[] acceptableIssuers) in /home/ivan_wl/devel/dotnet/WatsonTcp/WatsonTcp/WatsonTcpClientSslConfiguration.cs:line 108
   at System.Net.Security.SslStream.UserCertSelectionCallbackWrapper(String targetHost, X509CertificateCollection localCertificates, X509Certificate remoteCertificate, String[] acceptableIssuers)
   at System.Net.Security.SecureChannel.AcquireClientCredentials(Byte[]& thumbPrint)
   at System.Net.Security.SecureChannel.GenerateToken(ReadOnlySpan`1 inputBuffer, Byte[]& output)
   at System.Net.Security.SecureChannel.NextMessage(ReadOnlySpan`1 incomingBuffer)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Security.SslStream.AuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions)
   at System.Net.Security.SslStream.AuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
   at WatsonTcp.WatsonTcpClient.Connect() in /home/ivan_wl/devel/dotnet/WatsonTcp/WatsonTcp/WatsonTcpClient.cs:line 374
   at TestClient.TestClient.ConnectClient() in /home/ivan_wl/devel/dotnet/WatsonTcp/Test.Client/Program.cs:line 225
   at TestClient.TestClient.InitializeClient() in /home/ivan_wl/devel/dotnet/WatsonTcp/Test.Client/Program.cs:line 189
   at TestClient.TestClient.Main(String[] args) in /home/ivan_wl/devel/dotnet/WatsonTcp/Test.Client/Program.cs:line 24
```

**Comment by jchristn** [comment]
Hi @ivan7wl I haven't been doing any testing/development on .NET 6 since it's only a release candidate.  I will keep this open and add .NET 6 support when it becomes available (which I believe is next month).  However if you are able to identify the issue before then, I'll be happy to accept a PR on it.  Cheers, Joel

**Comment by jchristn** [comment]
Just tried on .NET 5, but I set ```Supply SSL certificate: [y/N]? n``` to ```y``` and it worked.  
![image](https://user-images.githubusercontent.com/1421081/136879887-7c8efa31-80dc-42b8-bae0-eae221de98f3.png)

You're right, it's not a framework issue, it only appears when no SSL certificate is supplied.
```
[Error    ] [WatsonTcpClient] exception encountered:
{
  "ClassName": "System.ArgumentOutOfRangeException",
  "Message": "Index was out of range. Must be non-negative and less than the size of the collection.",
  "Data": null,
  "InnerException": null,
  "HelpURL": null,
```
I will dig into this.  Thanks for letting me know!

**Comment by ivan7wl** [comment]
> For some reason, I'm not finding a way to get `SslStream.AuthenticateAsClient` to work without having specified a client certificate. I may have to amend the code to require it.

Thanks for the reply, so the workaround is, you also have to supply a client certificate for one-way authenticate (but not really used by the SSL connection)?
Does the server check the client certificate for one-way authenticate?

**Comment by jchristn** [comment]
This shouldn't have been closed quite yet, I still have to push to NuGet :)

Thank you @cbarraco for the timely fix!  I really appreciate it!
