### ISSUE TITLE
SocketException

### ISSUE THREAD

**Issue by Crushedice** [jchristn/WatsonTcp#54]
Greetings, 
As may expected with the debug Logs now at hand, i got the exception message finally. 
But still,  dont know how to solve it . 
After spending already hours on it , ill try to ask for help with it , 

Basicly i know from where the issue comes...  -  sending the stream with a dictionary as metadata.
If i remove the metadata, or, send a almost empty dictionary, it works fine... 
Maybe im overlooking something obvious..

The exception : 
```
Message build from stream exception:
System.Net.Sockets.SocketException (0x80004005): The operation completed successfully
   at WatsonTcp.Message.WatsonMessage.<ReadFromNetwork>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at WatsonTcp.Message.WatsonMessage.<BuildStream>d__40.MoveNext()
```

And the currently used method to send: 
     
 ```
public async Task UploadFileAsync(string zipfile)
        {
            
            var metadata = InputDictionary(); 
            using (FileStream source = new FileStream(zipfile, FileMode.Open, FileAccess.Read))
            { 
                
               await client.SendAsync(InputDictionary(), source.Length, source);
            }
        }
        
        private static Dictionary<object, object> InputDictionaryT()
        {
            Dictionary<object, object> ret = new Dictionary<object, object>();
            if (filemissD.Count > 0)
            {
                foreach (var x in filemissD)
                {
                    ret.Add(x.Key, x.Value);
                   
                }
            }
            return ret;
        }
```

**Comment by Crushedice** [comment]
-- Nevermind--
Found and resolved the issue.

Seems like the client did not wait for the upload to finish ( or more like , did not even really start to upload) 

and skipped ahead. with message " completed successfully "
